# permissions for end users to edit pachydermvaults.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachydermvault-editor-role
rules:
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermvaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachydermvaults/status
  verbs:
  - get
